apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ocexvb5q6-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ocexvb5q6-dotnet-basic-gitops